import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/components/themeProvider";
import Header from "@/components/layout/header";
import { Box } from "@mui/material";
import { CartProvider } from "@/context/cart";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <CartProvider>
            <>
            <Header />
            <Box sx={{ marginY: 4, minHeight: '60vh', height:'100%' }}>{children}</Box>
            <Footer />
            </>
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
