import "./globals.css";
import ThemeProvider from "@/components/themeProvider";
import Header from "@/components/layout/header";
import { Box } from "@mui/material";
import { CartProvider } from "@/context/cart";
import Footer from "@/components/layout/footer";
import { axiosInstance } from "@/client";
import ChatBotComponent from "@/components/shared/Chatbot";
import { Suspense } from "react";
import PageLoader from "@/components";

export async function generateMetadata({ params }: any) {
  const { subdomain } = await params;
  const { data } = await axiosInstance.get(
    `${process.env.NEXT_PUBLIC_API_URL}/tenant/get-tenant-config?tenant=${subdomain}`
  );
  return {
    title: data.config.metadata.title,
    description: data.config.metadata.description,
    openGraph: {
      title: data.config.metadata.title,
      description: data.config.metadata.description,
      images: { url: data.config.metadata.logo },
    },
  };
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   other: {
//     google: 'notranslate',
//   }
// };

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<any>;
}) {
  const { subdomain } = await params;
  return (
    <html lang="en" translate="no">
      <body>
        <ThemeProvider tenant={subdomain}>
          <CartProvider>
            <>
              <Header />
              <Suspense fallback={<PageLoader />}>
                <Box
                  sx={{
                    marginY: 4,
                    minHeight: "60vh",
                    height: "100%",
                    position: "relative",
                  }}
                >
                  {children}
                  <Box sx={{ position: "fixed", right: 0, bottom: 0 }}>
                    <ChatBotComponent />
                  </Box>
                </Box>
              </Suspense>
              <Footer />
            </>
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
